from typing import Protocol


class ObjectStorage(Protocol):
    async def check_ready(self) -> None: ...

    async def put(self, key: str, content: bytes, content_type: str) -> None: ...

    async def get(self, key: str) -> bytes: ...

    async def delete(self, key: str) -> None: ...
