"""add human handoffs

Revision ID: 826b5b312653
Revises: def39d1673ba
Create Date: 2026-07-17 03:08:51.208189
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "826b5b312653"
down_revision: str | None = "def39d1673ba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "handoff_requests",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_end_user_id", sa.Uuid(), nullable=False),
        sa.Column("assigned_staff_user_id", sa.Uuid(), nullable=True),
        sa.Column("closed_by_staff_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "closed",
                "cancelled",
                name="handoff_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_reason", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_handoff_requests_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_staff_user_id"],
            ["staff_users.id"],
            name=op.f("fk_handoff_requests_assigned_staff_user_id_staff_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_staff_user_id"],
            ["staff_users.id"],
            name=op.f("fk_handoff_requests_closed_by_staff_user_id_staff_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_handoff_requests_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_end_user_id"],
            ["end_users.id"],
            name=op.f("fk_handoff_requests_requested_by_end_user_id_end_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_handoff_requests_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_handoff_requests")),
    )
    op.create_index(
        op.f("ix_handoff_requests_application_id"),
        "handoff_requests",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_handoff_requests_assigned_staff_user_id"),
        "handoff_requests",
        ["assigned_staff_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_handoff_requests_conversation_id"),
        "handoff_requests",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_handoff_requests_requested_by_end_user_id"),
        "handoff_requests",
        ["requested_by_end_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_handoff_requests_tenant_id"), "handoff_requests", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_handoffs_tenant_status_created",
        "handoff_requests",
        ["tenant_id", "status", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_handoffs_active_conversation",
        "handoff_requests",
        ["tenant_id", "conversation_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'accepted')"),
        sqlite_where=sa.text("status IN ('pending', 'accepted')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_handoffs_active_conversation",
        table_name="handoff_requests",
        postgresql_where=sa.text("status IN ('pending', 'accepted')"),
        sqlite_where=sa.text("status IN ('pending', 'accepted')"),
    )
    op.drop_index("ix_handoffs_tenant_status_created", table_name="handoff_requests")
    op.drop_index(op.f("ix_handoff_requests_tenant_id"), table_name="handoff_requests")
    op.drop_index(
        op.f("ix_handoff_requests_requested_by_end_user_id"), table_name="handoff_requests"
    )
    op.drop_index(op.f("ix_handoff_requests_conversation_id"), table_name="handoff_requests")
    op.drop_index(op.f("ix_handoff_requests_assigned_staff_user_id"), table_name="handoff_requests")
    op.drop_index(op.f("ix_handoff_requests_application_id"), table_name="handoff_requests")
    op.drop_table("handoff_requests")
    # ### end Alembic commands ###
