"""add model gateway

Revision ID: a555eb7f278c
Revises: 3f4badb0b2f4
Create Date: 2026-07-17 02:49:04.707740
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a555eb7f278c"
down_revision: str | None = "3f4badb0b2f4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_provider_accounts",
        sa.Column("tenant_id", sa.Uuid(), nullable=True),
        sa.Column(
            "scope",
            sa.Enum(
                "platform",
                "tenant",
                name="provider_scope",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "fake",
                "openai_compatible",
                name="provider_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("api_key_ciphertext", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "ready",
                "disabled",
                name="provider_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope = 'platform' AND tenant_id IS NULL) OR (scope = 'tenant' AND tenant_id IS NOT NULL)",
            name=op.f("ck_ai_provider_accounts_provider_scope_owner"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_provider_accounts_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_provider_accounts")),
    )
    op.create_index(
        op.f("ix_ai_provider_accounts_scope"), "ai_provider_accounts", ["scope"], unique=False
    )
    op.create_index(
        op.f("ix_ai_provider_accounts_status"), "ai_provider_accounts", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_ai_provider_accounts_tenant_id"),
        "ai_provider_accounts",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "uq_provider_accounts_platform_name",
        "ai_provider_accounts",
        ["name"],
        unique=True,
        postgresql_where=sa.text("scope = 'platform'"),
        sqlite_where=sa.text("scope = 'platform'"),
    )
    op.create_index(
        "uq_provider_accounts_tenant_name",
        "ai_provider_accounts",
        ["tenant_id", "name"],
        unique=True,
        postgresql_where=sa.text("scope = 'tenant'"),
        sqlite_where=sa.text("scope = 'tenant'"),
    )
    op.create_table(
        "ai_model_configs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("provider_account_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("model_name", sa.String(length=200), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "chat", "embedding", name="model_purpose", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("embedding_dimension", sa.Integer(), nullable=True),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("input_price_micros_per_million", sa.BigInteger(), nullable=False),
        sa.Column("output_price_micros_per_million", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "inactive", "active", name="model_status", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(purpose = 'embedding' AND embedding_dimension IS NOT NULL) OR (purpose = 'chat' AND embedding_dimension IS NULL)",
            name=op.f("ck_ai_model_configs_model_embedding_dimension"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_account_id"],
            ["ai_provider_accounts.id"],
            name=op.f("fk_ai_model_configs_provider_account_id_ai_provider_accounts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_model_configs_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_model_configs")),
        sa.UniqueConstraint("tenant_id", "name", name=op.f("uq_ai_model_configs_tenant_id")),
    )
    op.create_index(
        op.f("ix_ai_model_configs_provider_account_id"),
        "ai_model_configs",
        ["provider_account_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_model_configs_tenant_id"), "ai_model_configs", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_ai_model_configs_tenant_purpose",
        "ai_model_configs",
        ["tenant_id", "purpose"],
        unique=False,
    )
    op.create_table(
        "application_model_bindings",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("model_config_id", sa.Uuid(), nullable=False),
        sa.Column(
            "purpose",
            sa.Enum(
                "chat",
                "embedding",
                name="binding_model_purpose",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_model_bindings_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["ai_model_configs.id"],
            name=op.f("fk_application_model_bindings_model_config_id_ai_model_configs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_application_model_bindings_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_model_bindings")),
        sa.UniqueConstraint(
            "tenant_id",
            "application_id",
            "purpose",
            name=op.f("uq_application_model_bindings_tenant_id"),
        ),
    )
    op.create_index(
        op.f("ix_application_model_bindings_application_id"),
        "application_model_bindings",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_model_bindings_model_config_id"),
        "application_model_bindings",
        ["model_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_model_bindings_tenant_id"),
        "application_model_bindings",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        "ix_model_bindings_tenant_app",
        "application_model_bindings",
        ["tenant_id", "application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_model_bindings_tenant_app", table_name="application_model_bindings")
    op.drop_index(
        op.f("ix_application_model_bindings_tenant_id"), table_name="application_model_bindings"
    )
    op.drop_index(
        op.f("ix_application_model_bindings_model_config_id"),
        table_name="application_model_bindings",
    )
    op.drop_index(
        op.f("ix_application_model_bindings_application_id"),
        table_name="application_model_bindings",
    )
    op.drop_table("application_model_bindings")
    op.drop_index("ix_ai_model_configs_tenant_purpose", table_name="ai_model_configs")
    op.drop_index(op.f("ix_ai_model_configs_tenant_id"), table_name="ai_model_configs")
    op.drop_index(op.f("ix_ai_model_configs_provider_account_id"), table_name="ai_model_configs")
    op.drop_table("ai_model_configs")
    op.drop_index(
        "uq_provider_accounts_tenant_name",
        table_name="ai_provider_accounts",
        postgresql_where=sa.text("scope = 'tenant'"),
        sqlite_where=sa.text("scope = 'tenant'"),
    )
    op.drop_index(
        "uq_provider_accounts_platform_name",
        table_name="ai_provider_accounts",
        postgresql_where=sa.text("scope = 'platform'"),
        sqlite_where=sa.text("scope = 'platform'"),
    )
    op.drop_index(op.f("ix_ai_provider_accounts_tenant_id"), table_name="ai_provider_accounts")
    op.drop_index(op.f("ix_ai_provider_accounts_status"), table_name="ai_provider_accounts")
    op.drop_index(op.f("ix_ai_provider_accounts_scope"), table_name="ai_provider_accounts")
    op.drop_table("ai_provider_accounts")
    # ### end Alembic commands ###
