"""add conversations and usage

Revision ID: c3b80989b7e8
Revises: a555eb7f278c
Create Date: 2026-07-17 02:52:47.031722
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c3b80989b7e8"
down_revision: str | None = "a555eb7f278c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "end_users",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("external_user_id", sa.String(length=128), nullable=False),
        sa.Column("profile", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_end_users_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_end_users_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_end_users")),
        sa.UniqueConstraint(
            "tenant_id", "application_id", "external_user_id", name=op.f("uq_end_users_tenant_id")
        ),
    )
    op.create_index(
        op.f("ix_end_users_application_id"), "end_users", ["application_id"], unique=False
    )
    op.create_index(
        "ix_end_users_tenant_application",
        "end_users",
        ["tenant_id", "application_id"],
        unique=False,
    )
    op.create_index(op.f("ix_end_users_tenant_id"), "end_users", ["tenant_id"], unique=False)
    op.create_table(
        "conversations",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("end_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "mode",
            sa.Enum(
                "ai", "human", name="conversation_mode", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "closed",
                name="conversation_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_conversations_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["end_user_id"],
            ["end_users.id"],
            name=op.f("fk_conversations_end_user_id_end_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_conversations_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
    )
    op.create_index(
        op.f("ix_conversations_application_id"), "conversations", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_end_user_id"), "conversations", ["end_user_id"], unique=False
    )
    op.create_index(
        "ix_conversations_tenant_application",
        "conversations",
        ["tenant_id", "application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_tenant_id"), "conversations", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_conversations_tenant_status", "conversations", ["tenant_id", "status"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("reply_to_message_id", sa.Uuid(), nullable=True),
        sa.Column(
            "sender",
            sa.Enum(
                "user",
                "ai",
                "agent",
                "system",
                name="message_sender",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("sender_staff_user_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "generating",
                "completed",
                "failed",
                name="message_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("model_config_id", sa.Uuid(), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("model_info", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_messages_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["ai_model_configs.id"],
            name=op.f("fk_messages_model_config_id_ai_model_configs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_message_id"],
            ["messages.id"],
            name=op.f("fk_messages_reply_to_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sender_staff_user_id"],
            ["staff_users.id"],
            name=op.f("fk_messages_sender_staff_user_id_staff_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_messages_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "tenant_id", "conversation_id", "idempotency_key", name=op.f("uq_messages_tenant_id")
        ),
    )
    op.create_index(
        op.f("ix_messages_application_id"), "messages", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_conversation_id"), "messages", ["conversation_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_reply_to_message_id"), "messages", ["reply_to_message_id"], unique=False
    )
    op.create_index(
        "ix_messages_tenant_conversation_created",
        "messages",
        ["tenant_id", "conversation_id", "created_at"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False)
    op.create_table(
        "ai_usage_records",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("model_config_id", sa.Uuid(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_micros", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_ai_usage_records_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_ai_usage_records_conversation_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_ai_usage_records_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["ai_model_configs.id"],
            name=op.f("fk_ai_usage_records_model_config_id_ai_model_configs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_ai_usage_records_tenant_id_tenants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage_records")),
        sa.UniqueConstraint("message_id", name=op.f("uq_ai_usage_records_message_id")),
    )
    op.create_index(
        op.f("ix_ai_usage_records_application_id"),
        "ai_usage_records",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_records_conversation_id"),
        "ai_usage_records",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_records_model_config_id"),
        "ai_usage_records",
        ["model_config_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_usage_records_tenant_id"), "ai_usage_records", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_ai_usage_tenant_application",
        "ai_usage_records",
        ["tenant_id", "application_id"],
        unique=False,
    )
    op.create_index(
        "ix_ai_usage_tenant_created", "ai_usage_records", ["tenant_id", "created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_usage_tenant_created", table_name="ai_usage_records")
    op.drop_index("ix_ai_usage_tenant_application", table_name="ai_usage_records")
    op.drop_index(op.f("ix_ai_usage_records_tenant_id"), table_name="ai_usage_records")
    op.drop_index(op.f("ix_ai_usage_records_model_config_id"), table_name="ai_usage_records")
    op.drop_index(op.f("ix_ai_usage_records_conversation_id"), table_name="ai_usage_records")
    op.drop_index(op.f("ix_ai_usage_records_application_id"), table_name="ai_usage_records")
    op.drop_table("ai_usage_records")
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_index("ix_messages_tenant_conversation_created", table_name="messages")
    op.drop_index(op.f("ix_messages_reply_to_message_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_conversation_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_application_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_conversations_tenant_status", table_name="conversations")
    op.drop_index(op.f("ix_conversations_tenant_id"), table_name="conversations")
    op.drop_index("ix_conversations_tenant_application", table_name="conversations")
    op.drop_index(op.f("ix_conversations_end_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_application_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_end_users_tenant_id"), table_name="end_users")
    op.drop_index("ix_end_users_tenant_application", table_name="end_users")
    op.drop_index(op.f("ix_end_users_application_id"), table_name="end_users")
    op.drop_table("end_users")
    # ### end Alembic commands ###
